### ISSUE TITLE
Broken with lodash@4

### ISSUE THREAD

**Issue by nkbt** [oozcitak/xmlbuilder-js#129]
Because it depends on `lodash: *`:

```
Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nkbt/mh/feed-router/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/Users/nkbt/mh/feed-router/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nkbt/mh/feed-router/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
```

Lodash changed the way things are packaged and now functions are available at `lodash/assign` without any namespacing.

**Comment by nkbt** [comment]
Apparently aws uses way too old xmlbuilder

```
├─┬ aws-sdk@2.4.3
│ └─┬ xmlbuilder@2.6.2
```

Closing now.

**Comment by MichaelCPell** [comment]
Sorry for not knowing, but what is the proper way to fix this?

**Comment by nkbt** [comment]
1. Switch to version dependency from *.
2. Update code for lodash 4.

I reckon it might be solved already...
