### ISSUE TITLE
Inline elements within Text Decorator throws error

### ISSUE THREAD

**Issue by wesrice** [oozcitak/xmlbuilder-js#171]
I'm trying to recreate the following xml structure using with following object notation.

```xml
<pc id="1">Hello <mrk id="m1" type="term">World</mrk>!</pc>
```

```js
{
  pc: {
    '#text': [
      'Hello',
      {
        mrk: {
          '#text': 'World',
          '@id': 'm1',
          '@type': 'term',
        },
      },
      '!',
    ],
    '@id': 1,
  },
}
```

However, the presence of the inline element is throwing the following error:
```
[...]/node_modules/xmlbuilder/lib/XMLText.js:15
        throw new Error("Missing element text");
        ^

Error: Missing element text
    at new XMLText ([...]/node_modules/xmlbuilder/lib/XMLText.js:15:15)
    at XMLElement.module.exports.XMLNode.text ([...]/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:92:28)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:84:30)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:81:32)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
    at XMLElement.module.exports.XMLNode.element ([...]/node_modules/xmlbuilder/lib/XMLNode.js:85:23)
```

I'm wondering if there is a different way that I should be approaching this problem, or is this a bug?

Fwiw, I'm working with XLIFF tranlation files, and this structure was taken from [an example in their specification](http://docs.oasis-open.org/xliff/xliff-core/v2.1/csprd01/xliff-core-v2.1-csprd01.html#fragid-example).

**Comment by oozcitak** [comment]
Sorry for the very late response. This is now fixed and will be included in the next npm release. Thank you for the bug report.
