### ISSUE TITLE
error when generating xml for json array

### ISSUE THREAD

**Issue by ericlu88** [oozcitak/xmlbuilder-js#82]
json object:
```javascript
{  root: [1, 2, 3] }
```

When i tried to build the xml for this object, I got the following error: 
```
TypeError: undefined is not a function
    at XMLElement.module.exports.XMLNode.element (/node_modules/xmlbuilder/lib/XMLNode.js:94:85)
    at XMLElement.module.exports.XMLNode.element (/node_modules/xmlbuilder/lib/XMLNode.js:64:28)
    at XMLElement.module.exports.XMLNode.element (/node_modules/xmlbuilder/lib/XMLNode.js:87:25)
    at new XMLBuilder (/node_modules/xmlbuilder/lib/XMLBuilder.js:25:19)
    at Object.module.exports.create (/node_modules/xmlbuilder/lib/index.js:11:12)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
```

Moreover, when I am trying to serialize this json object: 
```javascript
{  root: ['1', '2', '3'] }
```
I got this xml:
```xml
<root>
    <1/>
    <2/>
    <3/>
</root>
```
But what I really intend to have is:
```xml
<root>
    <element>1</element>
    <element>2</element>
    <element>3</element>
</root>
```
I can't figure out a way to achieve this. Appreciate your help.

PS: I am using `xmlbuilder 2.6.4`

**Comment by oozcitak** [comment]
Sorry for the late response. This is possible, but you need to repeat the node name, e.g:

```js
{ 
  root: [
    { element: "1" },
    { element: "2" },
    { element: "3" },
  ]
}
```
