### ISSUE TITLE
Building w/ emoji throws exception

### ISSUE THREAD

**Issue by dwbruhn** [oozcitak/xmlbuilder-js#98]
I tried your example code, but with emoji:

```
var builder = require('xmlbuilder');
var xml = builder.create('root')
  .ele('xmlbuilder')
    .ele('repo', {'type': 'git'}, 'test 🐀 here')
  .end({ pretty: true});

console.log(xml);
```

And got this:

```
/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLStringifier.js:149
        throw new Error("Invalid character (" + chr + ") in string: " + str +
              ^
Error: Invalid character (�) in string: test 🐀 here at index 5
    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLStringifier.js:149:15)
    at XMLStringifier.assertLegalChar (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
    at XMLStringifier.module.exports.XMLStringifier.eleText (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLStringifier.js:28:19)
    at new XMLText (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLText.js:19:35)
    at XMLElement.module.exports.XMLNode.text (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLNode.js:165:15)
    at XMLElement.module.exports.XMLNode.node (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLNode.js:157:15)
    at XMLElement.module.exports.XMLNode.element (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLNode.js:100:28)
    at XMLElement.module.exports.XMLNode.ele (/Users/dbruhn/repos/testXML/node_modules/xmlbuilder/lib/XMLNode.js:268:19)
    at Object.<anonymous> (/Users/dbruhn/repos/testXML/index.js:4:6)
    at Module._compile (module.js:456:26)
```

Any plans to support emoji? :smile:

**Comment by oozcitak** [comment]
Of course we support emoji :smile: but you need to set the `allowSurrogateChars` flag, e.g.:
```js
var xml = builder.create('root', { allowSurrogateChars:true })
```

**Comment by dwbruhn** [comment]
Awesome!
